name: Generate and Deploy Temperature Art

# Controls when the action will run.
# Runs on the 1st of every month at midnight UTC.
on:
  schedule:
    - cron: '0 0 1 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Installs the required Python packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Runs the Python script to generate the image
      - name: Generate visualization
        run: python generate_image.py

      # Deploys the generated image to the gh-pages branch
      - name="Deploy to GitHub Pages"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The branch the action should deploy to.
          publish_branch: gh-pages
          # The directory the action should publish.
          # We're publishing the root directory, which will contain the new image.
          publish_dir: .
          # Keep the existing files in the gh-pages branch
          keep_files: true
          # The user that will commit the changes
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Update temperature visualization'
